---
# Default application name
app_name: app

# Default deployment and application user
app_user_name: app

# Default application user home directory
app_config_path: "/home/{{ app_user_name }}"

# Default application image
app_image: dmdv/modern-go-bootstrap

# Default application version
app_version: latest
